// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Posterr.api.Data;

#nullable disable

namespace Posterr.api.Migrations
{
    [DbContext(typeof(PosterrDbContext))]
    [Migration("20240209182425_AddData_Posts")]
    partial class AddData_Posts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(777)
                        .HasColumnType("nvarchar(777)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bdc2aaa-3194-42bb-b1ee-6336bfb21567"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 1",
                            CreatedAt = new DateTime(2023, 1, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9358da1b-326a-42d6-b4eb-0238e599ae3e"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 2",
                            CreatedAt = new DateTime(2023, 2, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6305746-75cb-47ba-89b8-f2bc41a31f3e"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 3",
                            CreatedAt = new DateTime(2023, 3, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("27ec4e7b-8545-43e7-82d1-58f77cc21784"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 4",
                            CreatedAt = new DateTime(2023, 4, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f80c0f27-0ded-4cfc-805a-0f01874a30b2"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 5",
                            CreatedAt = new DateTime(2023, 5, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a6dfef05-f786-4583-8c87-c92709011d14"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 6",
                            CreatedAt = new DateTime(2023, 6, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("352b0d4f-6a40-4bab-b935-923d957507d5"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 7",
                            CreatedAt = new DateTime(2023, 7, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("267f8255-d03e-4f9f-8737-10e7e9202f84"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 8",
                            CreatedAt = new DateTime(2023, 8, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bf093646-d91e-486d-8c50-6c2d46f9f9e2"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 9",
                            CreatedAt = new DateTime(2023, 9, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("98b8a9a7-056c-4b8d-bbb9-29ca7b5e7264"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 10",
                            CreatedAt = new DateTime(2023, 10, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("87ed131d-9fe4-4fab-92bc-19c8a4ceea8d"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 11",
                            CreatedAt = new DateTime(2023, 11, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1a9b942f-4340-42e6-a019-ecfed2efd5ef"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 12",
                            CreatedAt = new DateTime(2023, 12, 1, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6dc0ec28-9642-4e1e-8ce0-c357101e7483"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 13",
                            CreatedAt = new DateTime(2023, 12, 2, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("705b2d11-68c1-4e0e-bbfa-f46e838d46c7"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 14",
                            CreatedAt = new DateTime(2023, 12, 3, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f2974844-3c80-487a-9cbf-31f6e6a36c68"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 15",
                            CreatedAt = new DateTime(2023, 12, 4, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b0d7d203-b9a2-4b94-910b-1bfcebd38368"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 16",
                            CreatedAt = new DateTime(2023, 12, 5, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef40579a-5609-4b92-bba3-c4ec6d8bbfc2"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 17",
                            CreatedAt = new DateTime(2023, 12, 6, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8dc323f5-7b82-43c4-928d-cf4558549c6d"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 18",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c00df53-6b0a-4def-8110-4cc8fa0c0adf"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 19",
                            CreatedAt = new DateTime(2023, 12, 8, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("36d09a34-f0e4-498e-89ae-de52647c09cc"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 20",
                            CreatedAt = new DateTime(2023, 12, 9, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b938296b-6efa-4b1c-8f08-a893620f6953"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 21",
                            CreatedAt = new DateTime(2023, 12, 10, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d936eb2c-d4f6-4725-a49b-f50fd1c4a719"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 22",
                            CreatedAt = new DateTime(2023, 12, 11, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d0c04c9e-ca41-46c7-af86-39ed994c160d"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 23",
                            CreatedAt = new DateTime(2023, 12, 12, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("246f31d1-6379-416e-a725-f85de2b91e8e"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 24",
                            CreatedAt = new DateTime(2023, 12, 13, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f362d36c-d949-40ba-97a2-4e91abd85c71"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 25",
                            CreatedAt = new DateTime(2023, 12, 14, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("279071fb-ab24-4af6-933c-e0f7b703c0db"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 26",
                            CreatedAt = new DateTime(2023, 12, 15, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d51f83b2-d19c-4f9f-987a-ded3c600f971"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 27",
                            CreatedAt = new DateTime(2023, 12, 16, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9d64f209-e3eb-4286-9477-bd094f8cc55c"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 28",
                            CreatedAt = new DateTime(2023, 12, 17, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("800c3a4f-696c-48b2-a807-fe4887b85f80"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 29",
                            CreatedAt = new DateTime(2023, 12, 18, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7315b7f5-6e9d-4800-9c22-c6913a900783"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 30",
                            CreatedAt = new DateTime(2023, 12, 19, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("036e16ed-dfbe-4423-87db-cd9e5f0569e0"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 31",
                            CreatedAt = new DateTime(2023, 12, 20, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad76ee94-1e7d-4e12-9834-fe7c1fde4b4c"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 32",
                            CreatedAt = new DateTime(2023, 12, 21, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("18db3103-af83-4575-9384-148b739e54e7"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 33",
                            CreatedAt = new DateTime(2023, 12, 22, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dd4e3040-c62b-4bd5-8fd6-31c967fc1ee8"),
                            AuthorId = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Content = "This is the content of post 34",
                            CreatedAt = new DateTime(2023, 12, 23, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("136e2fe7-d6d1-4867-9ee7-9200b480fd66"),
                            AuthorId = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Content = "This is the content of post 35",
                            CreatedAt = new DateTime(2023, 12, 24, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c3a33893-37c5-4f58-9f2d-c181ad85087b"),
                            AuthorId = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Content = "This is the content of post 36",
                            CreatedAt = new DateTime(2023, 12, 25, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fbe533bb-5cb3-499f-aafa-c2f4f8224798"),
                            AuthorId = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Content = "This is the content of post 37",
                            CreatedAt = new DateTime(2023, 12, 26, 11, 11, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Repost", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RepostedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Reposts");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c7e6d15-b97e-4076-b1a4-8d5de0257f0d"),
                            Email = "ross.geller@posterr.com",
                            FirstName = "Ross",
                            LastName = "Geller",
                            UserName = "ross.geller"
                        },
                        new
                        {
                            Id = new Guid("20443dc9-5383-4baa-853a-9ad81a81d5e6"),
                            Email = "monica.geller@posterr.com",
                            FirstName = "Monica",
                            LastName = "Geller",
                            UserName = "monica.geller"
                        },
                        new
                        {
                            Id = new Guid("4d519f73-0225-449d-a6e2-2ee7782ff8a3"),
                            Email = "joey.tribiani@posterr.com",
                            FirstName = "Joey",
                            LastName = "Tribiani",
                            UserName = "joey.tribiani"
                        },
                        new
                        {
                            Id = new Guid("bed94755-a97d-4423-abb6-1a6a6785f387"),
                            Email = "chandler.bing@posterr.com",
                            FirstName = "Chandler",
                            LastName = "Bing",
                            UserName = "chandler.bing"
                        });
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.HasOne("Posterr.api.Data.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Repost", b =>
                {
                    b.HasOne("Posterr.api.Data.Models.Post", "Post")
                        .WithMany("Reposts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Posterr.api.Data.Models.User", "User")
                        .WithMany("Reposts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.Navigation("Reposts");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Reposts");
                });
#pragma warning restore 612, 618
        }
    }
}
