// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Posterr.api.Data;

#nullable disable

namespace Posterr.api.Migrations
{
    [DbContext(typeof(PosterrDbContext))]
    [Migration("20240209143128_DatabaseSeed")]
    partial class DatabaseSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(777)
                        .HasColumnType("nvarchar(777)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Repost", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RepostedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Reposts");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22d23612-8102-49c9-94a8-ded4315571f2"),
                            Email = "ross.geller@posterr.com",
                            FirstName = "Ross",
                            LastName = "Geller",
                            UserName = "ross.geller"
                        },
                        new
                        {
                            Id = new Guid("5bd3b895-940e-457d-a6ba-cb13402bd7f1"),
                            Email = "ross.geller@posterr.com",
                            FirstName = "Monica",
                            LastName = "Geller",
                            UserName = "monica.geller"
                        },
                        new
                        {
                            Id = new Guid("feee69c1-3fc2-4076-8875-39326e89cd5e"),
                            Email = "joey.tribiani@posterr.com",
                            FirstName = "Joey",
                            LastName = "Tribiani",
                            UserName = "joey.tribiani"
                        },
                        new
                        {
                            Id = new Guid("12ccc641-89ce-4a13-bec8-fa48c3033303"),
                            Email = "chandler.bing@posterr.com",
                            FirstName = "Chandler",
                            LastName = "Bing",
                            UserName = "chandler.bing"
                        });
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.HasOne("Posterr.api.Data.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Repost", b =>
                {
                    b.HasOne("Posterr.api.Data.Models.Post", "Post")
                        .WithMany("Reposts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Posterr.api.Data.Models.User", "User")
                        .WithMany("Reposts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.Post", b =>
                {
                    b.Navigation("Reposts");
                });

            modelBuilder.Entity("Posterr.api.Data.Models.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Reposts");
                });
#pragma warning restore 612, 618
        }
    }
}
